// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@2.0.4";

// src/lib/mcp/tools/list-chords.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z } from "npm:zod@^3.23.8";

// src/data/chords.ts
var chords = [
  {
    name: "Em",
    fingering: ["0", "2", "2", "0", "0", "0"],
    fingers: ["", "2", "3", "", "", ""],
    commonSongs: ["Wonderwall - Oasis", "Creep - Radiohead", "Wish You Were Here - Pink Floyd"]
  },
  {
    name: "Am",
    fingering: ["x", "0", "2", "2", "1", "0"],
    fingers: ["", "", "2", "3", "1", ""],
    commonSongs: ["House of the Rising Sun - The Animals", "Stairway to Heaven - Led Zeppelin"]
  },
  {
    name: "C",
    fingering: ["x", "3", "2", "0", "1", "0"],
    fingers: ["", "3", "2", "", "1", ""],
    commonSongs: ["Let It Be - The Beatles", "Imagine - John Lennon", "Hallelujah - Leonard Cohen"]
  },
  {
    name: "G",
    fingering: ["3", "2", "0", "0", "3", "3"],
    fingers: ["2", "1", "", "", "3", "4"],
    commonSongs: ["Good Riddance - Green Day", "Wonderwall - Oasis", "Wish You Were Here - Pink Floyd"]
  },
  {
    name: "D",
    fingering: ["x", "x", "0", "2", "3", "2"],
    fingers: ["", "", "", "1", "3", "2"],
    commonSongs: ["Wonderwall - Oasis", "Free Fallin' - Tom Petty", "Good Riddance - Green Day"]
  },
  {
    name: "E",
    fingering: ["0", "2", "2", "1", "0", "0"],
    fingers: ["", "2", "3", "1", "", ""],
    commonSongs: ["Wild Thing", "Twist and Shout - The Beatles", "Gloria"]
  },
  {
    name: "A",
    fingering: ["x", "0", "2", "2", "2", "0"],
    fingers: ["", "", "1", "2", "3", ""],
    commonSongs: ["Free Fallin' - Tom Petty", "Wonderwall - Oasis", "Love Me Do - The Beatles"]
  },
  {
    name: "Dm",
    fingering: ["x", "x", "0", "2", "3", "1"],
    fingers: ["", "", "", "2", "3", "1"],
    commonSongs: ["Scarborough Fair", "Eleanor Rigby - The Beatles", "Mad World"]
  },
  {
    name: "F",
    fingering: ["1", "3", "3", "2", "1", "1"],
    fingers: ["1", "3", "4", "2", "1", "1"],
    commonSongs: ["Here Comes the Sun - The Beatles", "Hey Jude - The Beatles"]
  },
  {
    name: "B7",
    fingering: ["x", "2", "1", "2", "0", "2"],
    fingers: ["", "2", "1", "3", "", "4"],
    commonSongs: ["Love Me Tender - Elvis", "Blue Suede Shoes", "Stand By Me"]
  },
  {
    name: "Bm",
    fingering: ["x", "2", "4", "4", "3", "2"],
    fingers: ["", "1", "3", "4", "2", "1"],
    commonSongs: ["The Sound of Silence - Simon & Garfunkel", "Nothing Else Matters - Metallica"]
  },
  {
    name: "G7",
    fingering: ["3", "2", "0", "0", "0", "1"],
    fingers: ["3", "2", "", "", "", "1"],
    commonSongs: ["Margaritaville - Jimmy Buffett", "Sweet Home Alabama - Lynyrd Skynyrd"]
  },
  {
    name: "C7",
    fingering: ["x", "3", "2", "3", "1", "0"],
    fingers: ["", "3", "2", "4", "1", ""],
    commonSongs: ["Blue Suede Shoes - Elvis", "Johnny B. Goode - Chuck Berry"]
  },
  {
    name: "A7",
    fingering: ["x", "0", "2", "0", "2", "0"],
    fingers: ["", "", "2", "", "3", ""],
    commonSongs: ["Dead or Alive - Bon Jovi", "Folsom Prison Blues - Johnny Cash"]
  },
  {
    name: "D7",
    fingering: ["x", "x", "0", "2", "1", "2"],
    fingers: ["", "", "", "2", "1", "3"],
    commonSongs: ["Cripple Creek", "Old Joe Clark", "Will the Circle Be Unbroken"]
  },
  {
    name: "E7",
    fingering: ["0", "2", "0", "1", "0", "0"],
    fingers: ["", "2", "", "1", "", ""],
    commonSongs: ["Crossroads - Robert Johnson", "Pride and Joy - Stevie Ray Vaughan"]
  },
  {
    name: "Am7",
    fingering: ["x", "0", "2", "0", "1", "0"],
    fingers: ["", "", "2", "", "1", ""],
    commonSongs: ["Girl from Ipanema", "Autumn Leaves", "Fly Me to the Moon"]
  },
  {
    name: "Em7",
    fingering: ["0", "2", "0", "0", "0", "0"],
    fingers: ["", "2", "", "", "", ""],
    commonSongs: ["Blackbird - The Beatles", "The Scientist - Coldplay"]
  },
  {
    name: "Dm7",
    fingering: ["x", "x", "0", "2", "1", "1"],
    fingers: ["", "", "", "2", "1", "1"],
    commonSongs: ["Fly Me to the Moon", "Autumn Leaves", "Summertime"]
  },
  {
    name: "Cmaj7",
    fingering: ["x", "3", "2", "0", "0", "0"],
    fingers: ["", "2", "1", "", "", ""],
    commonSongs: ["Imagine - John Lennon", "The Girl from Ipanema", "Wonderwall - Oasis"]
  },
  {
    name: "Fmaj7",
    fingering: ["1", "3", "3", "2", "1", "0"],
    fingers: ["1", "3", "4", "2", "1", ""],
    commonSongs: ["Here Comes the Sun - The Beatles", "Just the Way You Are - Billy Joel"]
  },
  {
    name: "Gsus4",
    fingering: ["3", "3", "0", "0", "1", "3"],
    fingers: ["2", "3", "", "", "1", "4"],
    commonSongs: ["Pinball Wizard - The Who", "Behind Blue Eyes - The Who"]
  },
  {
    name: "Dsus4",
    fingering: ["x", "x", "0", "2", "3", "3"],
    fingers: ["", "", "", "1", "2", "3"],
    commonSongs: ["Blackbird - The Beatles", "Dust in the Wind - Kansas"]
  },
  {
    name: "Cadd9",
    fingering: ["x", "3", "2", "0", "3", "0"],
    fingers: ["", "2", "1", "", "3", ""],
    commonSongs: ["High and Dry - Radiohead", "Champagne Supernova - Oasis"]
  },
  {
    name: "G/B",
    fingering: ["x", "2", "0", "0", "3", "3"],
    fingers: ["", "1", "", "", "2", "3"],
    commonSongs: ["Wonderwall - Oasis", "Good Riddance - Green Day"]
  },
  {
    name: "F#m",
    fingering: ["2", "4", "4", "2", "2", "2"],
    fingers: ["1", "3", "4", "1", "1", "1"],
    commonSongs: ["Hotel California - Eagles", "Stairway to Heaven - Led Zeppelin"]
  },
  {
    name: "Bb",
    fingering: ["x", "1", "3", "3", "3", "1"],
    fingers: ["", "1", "2", "3", "4", "1"],
    commonSongs: ["Let It Be - The Beatles", "Hey Jude - The Beatles"]
  },
  {
    name: "A#dim",
    fingering: ["x", "1", "2", "0", "2", "0"],
    fingers: ["", "1", "2", "", "3", ""],
    commonSongs: ["Cry Me a River", "As Time Goes By", "Yesterday - The Beatles"]
  },
  {
    name: "Esus4",
    fingering: ["0", "2", "2", "2", "0", "0"],
    fingers: ["", "1", "2", "3", "", ""],
    commonSongs: ["The Who - Pinball Wizard", "Pink Floyd - Wish You Were Here"]
  },
  {
    name: "Asus4",
    fingering: ["x", "0", "2", "2", "3", "0"],
    fingers: ["", "", "1", "2", "3", ""],
    commonSongs: ["Free Fallin' - Tom Petty", "Wonderwall - Oasis", "Champagne Supernova - Oasis"]
  }
];

// src/i18n/locales/en-US/content.json
var content_default = {
  titles: {
    app: "30 Chords in 30 Days",
    app_subtitle: "Learn guitar gradually and consistently",
    daily_chord: "Daily Chord",
    progress_tracker: "Progress Tracker",
    guitar_fundamentals: "Guitar Fundamentals",
    important: "Important:",
    intro_lesson: "Introductory Lesson - Guitar Fundamentals"
  },
  descriptions: {
    app: "Your daily guitar learning journey",
    chord_practice: "Practice and master new chords",
    progress: "Track your daily progress",
    intro_required: "Complete the Introductory Lesson (Day 0) first before proceeding to chords!"
  },
  tips: {
    finger_position: "Position your fingers correctly",
    practice_daily: "Practice daily for best results",
    be_patient: "Be patient, progress comes with time",
    tip: "Tip"
  },
  chords: {
    Em: {
      fullName: "E minor",
      difficulty: "Easy",
      instructions: "Place finger 2 on the second fret of the A string (5th string) and finger 3 on the second fret of the D string (4th string). Leave the other strings open.",
      tip: "This is one of the easiest chords! Make sure your fingers are curved and don't touch the other strings."
    },
    Am: {
      fullName: "A minor",
      difficulty: "Easy",
      instructions: "Place finger 1 on the first fret of the B string, finger 2 on the second fret of the D string, and finger 3 on the second fret of the G string. Don't play the low E string.",
      tip: "Keep your thumb behind the guitar neck for better support. This chord appears in thousands of songs!"
    },
    C: {
      fullName: "C major",
      difficulty: "Medium",
      instructions: "Finger 1 on the first fret of the B string, finger 2 on the second fret of the D string, finger 3 on the third fret of the A string. G and high E strings remain open.",
      tip: "This chord can be a bit challenging at first. Make sure to press the strings firmly and that each note sounds clean."
    },
    G: {
      fullName: "G major",
      difficulty: "Medium",
      instructions: "Finger 1 on the second fret of the A string, finger 2 on the third fret of the low E string, finger 3 on the third fret of the B string, finger 4 on the third fret of the high E string.",
      tip: "Use your fingertips and keep them curved. It's normal for this chord to be difficult at first, but with practice it becomes natural."
    },
    D: {
      fullName: "D major",
      difficulty: "Medium",
      instructions: "Finger 1 on the second fret of the G string, finger 2 on the second fret of the high E string, finger 3 on the third fret of the B string. Only play the top 4 strings.",
      tip: "Focus on playing only the strings that should sound. The two lowest strings (E and A) should not be played in this chord."
    },
    E: {
      fullName: "E major",
      difficulty: "Easy",
      instructions: "Finger 1 on the first fret of the G string, finger 2 on the second fret of the A string, finger 3 on the second fret of the D string. The E strings remain open.",
      tip: "This is a fundamental chord! Make sure finger 1 doesn't accidentally touch the B string."
    },
    A: {
      fullName: "A major",
      difficulty: "Medium",
      instructions: "Place fingers 1, 2, and 3 all on the second fret of the D, G, and B strings respectively. The A string stays open, high E open.",
      tip: "Try using just one finger (like a barre) to press the three strings on the second fret - this will make transitions to other chords easier."
    },
    Dm: {
      fullName: "D minor",
      difficulty: "Medium",
      instructions: "Finger 1 on the first fret of the high E string, finger 2 on the second fret of the G string, finger 3 on the third fret of the B string. Play only the top 4 strings.",
      tip: "Like the D major chord, avoid playing the low E and A strings. The sound should be more melancholic than D major."
    },
    F: {
      fullName: "F major",
      difficulty: "Hard",
      instructions: "This is a barre chord. Use finger 1 to press all strings on the first fret, then place the other fingers: finger 2 on the second fret of the G string, fingers 3 and 4 on the third fret of the A and D strings.",
      tip: "This is the first really challenging chord! The barre requires strength and practice. Start by practicing just the barre, then add the other fingers."
    },
    B7: {
      fullName: "B seventh",
      difficulty: "Medium",
      instructions: "Finger 1 on the first fret of the D string, finger 2 on the second fret of the A string, finger 3 on the second fret of the G string, finger 4 on the second fret of the high E string.",
      tip: "This chord has a jazzy sound and is widely used in blues. The B string stays open, creating an interesting sound."
    },
    Bm: {
      fullName: "B minor",
      difficulty: "Hard",
      instructions: "Use a mini-barre with finger 1 on the second fret (A and high E strings), finger 2 on the third fret of the B string, fingers 3 and 4 on the fourth fret of the D and G strings.",
      tip: "This is another challenging chord. You can use a full barre on the second fret if it's more comfortable."
    },
    G7: {
      fullName: "G seventh",
      difficulty: "Easy",
      instructions: "Finger 1 on the first fret of the high E string, finger 2 on the second fret of the A string, finger 3 on the third fret of the low E string. The D, G, and B strings remain open.",
      tip: "This chord is very similar to G major, but with the pinky on the first fret of the high E string. It gives a more bluesy sound."
    },
    C7: {
      fullName: "C seventh",
      difficulty: "Medium",
      instructions: "Finger 1 on the first fret of the B string, finger 2 on the second fret of the D string, finger 3 on the third fret of the A string, finger 4 on the third fret of the G string.",
      tip: "Based on the C major chord, but with an additional note that creates tension. Widely used in progressions going to F."
    },
    A7: {
      fullName: "A seventh",
      difficulty: "Easy",
      instructions: "Finger 2 on the second fret of the D string, finger 3 on the second fret of the B string. The A, G, and E strings remain open.",
      tip: "One of the easiest seventh chords! Widely used in blues and country. It has an open and resolute sound."
    },
    D7: {
      fullName: "D seventh",
      difficulty: "Easy",
      instructions: "Finger 1 on the first fret of the B string, finger 2 on the second fret of the G string, finger 3 on the second fret of the high E string. D string stays open.",
      tip: "Very similar to D major, but with finger 1 on the first fret of the B string. Creates tension that resolves well to G."
    },
    E7: {
      fullName: "E seventh",
      difficulty: "Easy",
      instructions: "Finger 1 on the first fret of the G string, finger 2 on the second fret of the A string. All other strings remain open.",
      tip: "Even easier than E major! Just remove one finger from the E chord. Widely used in blues and rock."
    },
    Am7: {
      fullName: "A minor seventh",
      difficulty: "Easy",
      instructions: "Finger 1 on the first fret of the B string, finger 2 on the second fret of the D string. The A, G, and E strings remain open.",
      tip: "A softer version of Am. Widely used in jazz and bossa nova. It has a more sophisticated and relaxing sound."
    },
    Em7: {
      fullName: "E minor seventh",
      difficulty: "Easy",
      instructions: "Only finger 2 on the second fret of the A string. All other strings remain open.",
      tip: "The easiest chord of all! Just one finger. It has a very open and ethereal sound, perfect for ballads."
    },
    Dm7: {
      fullName: "D minor seventh",
      difficulty: "Medium",
      instructions: "Use finger 1 to make a mini-barre on the first fret (B and high E strings), finger 2 on the second fret of the G string.",
      tip: "A jazzy and sophisticated sound. The mini-barre can be challenging at first, but it's very useful to master."
    },
    Cmaj7: {
      fullName: "C major seventh",
      difficulty: "Easy",
      instructions: "Finger 1 on the second fret of the D string, finger 2 on the third fret of the A string. The G, B, and E strings remain open.",
      tip: "A very beautiful and sophisticated chord. Softer than C7, it has a dreamy sound perfect for ballads."
    },
    Fmaj7: {
      fullName: "F major seventh",
      difficulty: "Hard",
      instructions: "Barre with finger 1 on the first fret (low E and B strings), finger 2 on the second fret of the G string, fingers 3 and 4 on the third fret of the A and D strings.",
      tip: "Similar to F major, but without pressing the high E string in the barre. Creates a more open and jazzy sound."
    },
    Gsus4: {
      fullName: "G suspended fourth",
      difficulty: "Medium",
      instructions: "Finger 1 on the first fret of the B string, finger 2 on the third fret of the low E string, finger 3 on the third fret of the A string, finger 4 on the third fret of the high E string.",
      tip: "A widely used passing chord. Creates suspense and tension that resolves well to G major. Widely used in rock."
    },
    Dsus4: {
      fullName: "D suspended fourth",
      difficulty: "Medium",
      instructions: "Finger 1 on the second fret of the G string, finger 2 on the third fret of the B string, finger 3 on the third fret of the high E string.",
      tip: "Creates beautiful tension that resolves to D major. Widely used in folk and country songs to add movement."
    },
    Cadd9: {
      fullName: "C major add ninth",
      difficulty: "Medium",
      instructions: "Finger 1 on the second fret of the D string, finger 2 on the third fret of the A string, finger 3 on the third fret of the B string.",
      tip: "A more colorful version of C major. Adds a note that gives a more modern and interesting sound."
    },
    "G/B": {
      fullName: "G over B",
      difficulty: "Medium",
      instructions: "Finger 1 on the second fret of the A string, finger 2 on the third fret of the B string, finger 3 on the third fret of the high E string.",
      tip: "A very useful passing chord. The different bass creates a melodic line in the bass, widely used in descending progressions."
    },
    "F#m": {
      fullName: "F sharp minor",
      difficulty: "Hard",
      instructions: "Full barre with finger 1 on the second fret, finger 3 on the fourth fret of the A string, finger 4 on the fourth fret of the D string.",
      tip: "Based on the Em shape, but with a barre on the second fret. This is good practice for mastering barres."
    },
    Bb: {
      fullName: "B flat major",
      difficulty: "Hard",
      instructions: "Barre with finger 1 on the first fret (A and high E strings), finger 2 on the third fret of the D string, fingers 3 and 4 on the third fret of the G and B strings.",
      tip: "Another barre chord. Very common in songs in flat keys. Practice the barre separately first."
    },
    "A#dim": {
      fullName: "A sharp diminished",
      difficulty: "Medium",
      instructions: "Finger 1 on the first fret of the A string, finger 2 on the second fret of the D string, finger 3 on the second fret of the B string.",
      tip: "A passing chord with a unique and mysterious sound. Widely used to create tension and interesting harmonic movement."
    },
    Esus4: {
      fullName: "E suspended fourth",
      difficulty: "Easy",
      instructions: "Finger 1 on the second fret of the A string, finger 2 on the second fret of the D string, finger 3 on the second fret of the G string.",
      tip: "Creates beautiful tension that resolves to E major. Widely used at the end of musical phrases to add drama."
    },
    Asus4: {
      fullName: "A suspended fourth",
      difficulty: "Easy",
      instructions: "Finger 1 on the second fret of the D string, finger 2 on the second fret of the G string, finger 3 on the third fret of the B string. The A and high E strings remain open.",
      tip: "\u{1F389} Congratulations on reaching Day 30! This chord is perfect for 'Free Fallin'' by Tom Petty. It creates beautiful tension that resolves to A major. Practice switching between D, Dsus4, and Asus4 - this is the entire song! Try with a capo on fret 3 to match the original recording."
    }
  },
  bonus: {
    title: 'Bonus Final Lesson: Course Completion \u2013 Play "Love Me Do" by The Beatles! \u{1F389}',
    subtitle: "You've done it! You've mastered 30 essential chords in 30 days through gradual, consistent practice.",
    description: `This foundation means you can now play hundreds of songs \u2013 and to celebrate, here's one of the simplest and most iconic full songs you can play right now: "Love Me Do" by The Beatles (their very first single!).`,
    why_perfect: "This song is perfect for beginners finishing a chord course: it uses only 3 basic open chords (G, C, D \u2013 some of the first ones you likely learned), has a fun, upbeat rhythm, and includes the famous harmonica riff (which you can play on guitar if you want). It's energetic, instantly recognizable, and will make you feel like a true Beatle!",
    chord_review: "Chord Review Diagrams",
    chord_review_desc: "These are core chords from your 30-day journey:",
    chord_g: "G: 320003",
    chord_c: "C: x32010",
    chord_d: "D: xx0232 (optional for the bridge \u2013 the main song is mostly G and C!)",
    how_to_play: "How to Play",
    no_capo: "No capo needed \u2013 play in standard tuning.",
    strumming_pattern: "Easy Strumming Pattern:",
    strumming_pattern_desc: "Down-Down-Up-Up-Down-Up (D DU UDU) \u2013 keep it steady and fun, like a 60s rock beat. Start slow!",
    structure: "The song is mostly verse + chorus repeating G and C, with a short bridge.",
    verse_chorus: "Verse/Chorus (Chords over Lyrics):",
    bridge: "Bridge (optional \u2013 adds D):",
    harmonica_riff: "Harmonica Riff on Guitar (Bonus Fun):",
    harmonica_riff_desc: "The famous intro riff is simple single notes on the guitar \u2013 easy to add once you're comfortable with the chords.",
    important_tips: "Important Tips",
    tip_1: "Focus on quick changes between G and C \u2013 you've practiced these tons!",
    tip_2: "Sing along loudly \u2013 it's a feel-good song that encourages energy.",
    tip_3: "This proves how far you've come: just a few basic chords create a worldwide hit!",
    play_audio: "Play Audio",
    final_message: "Congratulations! You've completed 30 Chords in 30 Days + this bonus song. You're now a real guitarist \u2013 keep playing every day and share your version of 'Love Me Do'! \u{1F3B8}"
  }
};

// src/i18n/locales/pt-BR/content.json
var content_default2 = {
  titles: {
    app: "30 Acordes em 30 Dias",
    app_subtitle: "Aprenda viol\xE3o de forma gradual e consistente",
    daily_chord: "Acorde Di\xE1rio",
    progress_tracker: "Acompanhamento de Progresso",
    guitar_fundamentals: "Fundamentos do Viol\xE3o",
    important: "Importante:",
    intro_lesson: "Li\xE7\xE3o Introdut\xF3ria - Fundamentos do Viol\xE3o"
  },
  descriptions: {
    app: "Sua jornada di\xE1ria de aprendizado de viol\xE3o",
    chord_practice: "Pratique e domine novos acordes",
    progress: "Acompanhe seu progresso di\xE1rio",
    intro_required: "Complete primeiro a Li\xE7\xE3o Introdut\xF3ria (Dia 0) antes de prosseguir para os acordes!"
  },
  tips: {
    finger_position: "Posicione os dedos corretamente",
    practice_daily: "Pratique todos os dias para melhores resultados",
    be_patient: "Seja paciente, o progresso vem com o tempo",
    tip: "Dica"
  },
  chords: {
    Em: {
      fullName: "Mi menor",
      difficulty: "F\xE1cil",
      instructions: "Coloque o dedo 2 na segunda casa da corda A (5\xAA corda) e o dedo 3 na segunda casa da corda D (4\xAA corda). As outras cordas ficam soltas.",
      tip: "Este \xE9 um dos acordes mais f\xE1ceis! Certifique-se de que os dedos est\xE3o curvados e n\xE3o tocam nas outras cordas."
    },
    Am: {
      fullName: "L\xE1 menor",
      difficulty: "F\xE1cil",
      instructions: "Coloque o dedo 1 na primeira casa da corda B, dedo 2 na segunda casa da corda D, e dedo 3 na segunda casa da corda G. N\xE3o toque a corda E grave.",
      tip: "Mantenha o polegar atr\xE1s do bra\xE7o do viol\xE3o para ter melhor apoio. Este acorde aparece em milhares de m\xFAsicas!"
    },
    C: {
      fullName: "D\xF3 maior",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na primeira casa da corda B, dedo 2 na segunda casa da corda D, dedo 3 na terceira casa da corda A. Corda G e E aguda ficam soltas.",
      tip: "Este acorde pode ser um pouco desafiador no in\xEDcio. Certifique-se de pressionar bem as cordas e que cada nota soe limpa."
    },
    G: {
      fullName: "Sol maior",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na segunda casa da corda A, dedo 2 na terceira casa da corda E grave, dedo 3 na terceira casa da corda B, dedo 4 na terceira casa da corda E aguda.",
      tip: "Use a ponta dos dedos e mantenha-os curvados. \xC9 normal este acorde ser dif\xEDcil no come\xE7o, mas com pr\xE1tica fica natural."
    },
    D: {
      fullName: "R\xE9 maior",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na segunda casa da corda G, dedo 2 na segunda casa da corda E aguda, dedo 3 na terceira casa da corda B. S\xF3 toque as 4 cordas mais agudas.",
      tip: "Concentre-se em tocar apenas as cordas que devem soar. As duas cordas mais graves (E e A) n\xE3o devem ser tocadas neste acorde."
    },
    E: {
      fullName: "Mi maior",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na primeira casa da corda G, dedo 2 na segunda casa da corda A, dedo 3 na segunda casa da corda D. As cordas E ficam soltas.",
      tip: "Este \xE9 um acorde fundamental! Certifique-se de que o dedo 1 n\xE3o toque na corda B acidentalmente."
    },
    A: {
      fullName: "L\xE1 maior",
      difficulty: "M\xE9dio",
      instructions: "Coloque os dedos 1, 2 e 3 todos na segunda casa das cordas D, G e B respectivamente. A corda A fica solta, E aguda solta.",
      tip: "Tente usar apenas um dedo (como uma pestana) para pressionar as tr\xEAs cordas na segunda casa - isso facilitar\xE1 a transi\xE7\xE3o para outros acordes."
    },
    Dm: {
      fullName: "R\xE9 menor",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na primeira casa da corda E aguda, dedo 2 na segunda casa da corda G, dedo 3 na terceira casa da corda B. Toque apenas as 4 cordas mais agudas.",
      tip: "Como o acorde de D maior, evite tocar as cordas E grave e A. O som deve ser mais melanc\xF3lico que o D maior."
    },
    F: {
      fullName: "F\xE1 maior",
      difficulty: "Dif\xEDcil",
      instructions: "Este \xE9 um acorde com pestana. Use o dedo 1 para pressionar todas as cordas na primeira casa, depois coloque os outros dedos: dedo 2 na segunda casa da corda G, dedos 3 e 4 na terceira casa das cordas A e D.",
      tip: "Este \xE9 o primeiro acorde realmente desafiador! A pestana requer for\xE7a e pr\xE1tica. Comece praticando apenas a pestana, depois adicione os outros dedos."
    },
    B7: {
      fullName: "Si com s\xE9tima",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na primeira casa da corda D, dedo 2 na segunda casa da corda A, dedo 3 na segunda casa da corda G, dedo 4 na segunda casa da corda E aguda.",
      tip: "Este acorde tem uma sonoridade jazzy e \xE9 muito usado em blues. A corda B fica solta, criando um som interessante."
    },
    Bm: {
      fullName: "Si menor",
      difficulty: "Dif\xEDcil",
      instructions: "Use uma mini-pestana com o dedo 1 na segunda casa (cordas A e E aguda), dedo 2 na terceira casa da corda B, dedos 3 e 4 na quarta casa das cordas D e G.",
      tip: "Este \xE9 outro acorde desafiador. Voc\xEA pode usar uma pestana completa na segunda casa se for mais confort\xE1vel."
    },
    G7: {
      fullName: "Sol com s\xE9tima",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na primeira casa da corda E aguda, dedo 2 na segunda casa da corda A, dedo 3 na terceira casa da corda E grave. As cordas D, G e B ficam soltas.",
      tip: "Este acorde \xE9 muito parecido com o G maior, mas com o dedo mindinho na primeira casa da corda E aguda. D\xE1 um som mais bluesy."
    },
    C7: {
      fullName: "D\xF3 com s\xE9tima",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na primeira casa da corda B, dedo 2 na segunda casa da corda D, dedo 3 na terceira casa da corda A, dedo 4 na terceira casa da corda G.",
      tip: "Baseado no acorde C maior, mas com uma nota adicional que cria tens\xE3o. Muito usado em progress\xF5es que v\xE3o para F."
    },
    A7: {
      fullName: "L\xE1 com s\xE9tima",
      difficulty: "F\xE1cil",
      instructions: "Dedo 2 na segunda casa da corda D, dedo 3 na segunda casa da corda B. As cordas A, G e E ficam soltas.",
      tip: "Um dos acordes de s\xE9tima mais f\xE1ceis! Muito usado em blues e country. Tem um som aberto e resoluto."
    },
    D7: {
      fullName: "R\xE9 com s\xE9tima",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na primeira casa da corda B, dedo 2 na segunda casa da corda G, dedo 3 na segunda casa da corda E aguda. Corda D fica solta.",
      tip: "Muito similar ao D maior, mas com o dedo 1 na primeira casa da corda B. Cria uma tens\xE3o que resolve bem no G."
    },
    E7: {
      fullName: "Mi com s\xE9tima",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na primeira casa da corda G, dedo 2 na segunda casa da corda A. Todas as outras cordas ficam soltas.",
      tip: "Ainda mais f\xE1cil que o E maior! Remove apenas um dedo do acorde de E. Muito usado em blues e rock."
    },
    Am7: {
      fullName: "L\xE1 menor com s\xE9tima",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na primeira casa da corda B, dedo 2 na segunda casa da corda D. As cordas A, G e E ficam soltas.",
      tip: "Uma vers\xE3o mais suave do Am. Muito usado em jazz e bossa nova. Tem um som mais sofisticado e relaxante."
    },
    Em7: {
      fullName: "Mi menor com s\xE9tima",
      difficulty: "F\xE1cil",
      instructions: "Apenas o dedo 2 na segunda casa da corda A. Todas as outras cordas ficam soltas.",
      tip: "O acorde mais f\xE1cil de todos! Apenas um dedo. Tem um som muito aberto e et\xE9reo, perfeito para baladas."
    },
    Dm7: {
      fullName: "R\xE9 menor com s\xE9tima",
      difficulty: "M\xE9dio",
      instructions: "Use o dedo 1 para fazer uma mini-pestana na primeira casa (cordas B e E aguda), dedo 2 na segunda casa da corda G.",
      tip: "Uma sonoridade jazzy e sofisticada. A mini-pestana pode ser desafiadora no in\xEDcio, mas \xE9 muito \xFAtil de dominar."
    },
    Cmaj7: {
      fullName: "D\xF3 maior com s\xE9tima maior",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na segunda casa da corda D, dedo 2 na terceira casa da corda A. As cordas G, B e E ficam soltas.",
      tip: "Um acorde muito bonito e sofisticado. Mais suave que o C7, tem uma sonoridade dreamy perfeita para baladas."
    },
    Fmaj7: {
      fullName: "F\xE1 maior com s\xE9tima maior",
      difficulty: "Dif\xEDcil",
      instructions: "Pestana com dedo 1 na primeira casa (cordas E grave e B), dedo 2 na segunda casa da corda G, dedos 3 e 4 na terceira casa das cordas A e D.",
      tip: "Similar ao F maior, mas sem pressionar a corda E aguda na pestana. Cria um som mais aberto e jazz."
    },
    Gsus4: {
      fullName: "Sol suspenso quarta",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na primeira casa da corda B, dedo 2 na terceira casa da corda E grave, dedo 3 na terceira casa da corda A, dedo 4 na terceira casa da corda E aguda.",
      tip: "Acorde de passagem muito usado. Cria suspense e tens\xE3o que resolve bem no G maior. Muito usado no rock."
    },
    Dsus4: {
      fullName: "R\xE9 suspenso quarta",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na segunda casa da corda G, dedo 2 na terceira casa da corda B, dedo 3 na terceira casa da corda E aguda.",
      tip: "Cria uma bela tens\xE3o que resolve no D maior. Muito usado em m\xFAsicas folk e country para adicionar movimento."
    },
    Cadd9: {
      fullName: "D\xF3 maior com nona adicionada",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na segunda casa da corda D, dedo 2 na terceira casa da corda A, dedo 3 na terceira casa da corda B.",
      tip: "Uma vers\xE3o mais colorida do C maior. Adiciona uma nota que d\xE1 um som mais moderno e interessante."
    },
    "G/B": {
      fullName: "Sol com baixo em Si",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na segunda casa da corda A, dedo 2 na terceira casa da corda B, dedo 3 na terceira casa da corda E aguda.",
      tip: "Acorde de passagem muito \xFAtil. O baixo diferente cria uma linha mel\xF3dica no baixo, muito usado em progress\xF5es descendentes."
    },
    "F#m": {
      fullName: "F\xE1 sustenido menor",
      difficulty: "Dif\xEDcil",
      instructions: "Pestana completa com dedo 1 na segunda casa, dedo 3 na quarta casa da corda A, dedo 4 na quarta casa da corda D.",
      tip: "Baseado na forma do Em, mas com pestana na segunda casa. Este \xE9 um bom exerc\xEDcio para dominar pestanas."
    },
    Bb: {
      fullName: "Si bemol maior",
      difficulty: "Dif\xEDcil",
      instructions: "Pestana com dedo 1 na primeira casa (cordas A e E aguda), dedo 2 na terceira casa da corda D, dedos 3 e 4 na terceira casa das cordas G e B.",
      tip: "Outro acorde com pestana. Muito comum em m\xFAsicas em tonalidades com bem\xF3is. Pratique a pestana separadamente primeiro."
    },
    "A#dim": {
      fullName: "L\xE1 sustenido diminuto",
      difficulty: "M\xE9dio",
      instructions: "Dedo 1 na primeira casa da corda A, dedo 2 na segunda casa da corda D, dedo 3 na segunda casa da corda B.",
      tip: "Acorde de passagem com sonoridade \xFAnica e misteriosa. Muito usado para criar tens\xE3o e movimento harm\xF4nico interessante."
    },
    Esus4: {
      fullName: "Mi suspenso quarta",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na segunda casa da corda A, dedo 2 na segunda casa da corda D, dedo 3 na segunda casa da corda G.",
      tip: "Cria uma bela tens\xE3o que resolve no E maior. Muito usado no final de frases musicais para adicionar drama."
    },
    Asus4: {
      fullName: "L\xE1 suspenso quarta",
      difficulty: "F\xE1cil",
      instructions: "Dedo 1 na segunda casa da corda D, dedo 2 na segunda casa da corda G, dedo 3 na terceira casa da corda B. As cordas A e E aguda ficam soltas.",
      tip: "\u{1F389} Parab\xE9ns por chegar ao Dia 30! Este acorde \xE9 perfeito para 'Free Fallin'' de Tom Petty. Cria uma bela tens\xE3o que resolve no A maior. Pratique alternando entre D, Dsus4 e Asus4 - essa \xE9 a m\xFAsica inteira! Experimente com capotraste no traste 3 para tocar igual \xE0 grava\xE7\xE3o original."
    }
  },
  bonus: {
    title: 'Li\xE7\xE3o B\xF4nus Final: Conclus\xE3o do Curso \u2013 Toque "Love Me Do" dos Beatles! \u{1F389}',
    subtitle: "Voc\xEA conseguiu! Voc\xEA dominou 30 acordes essenciais em 30 dias atrav\xE9s de pr\xE1tica gradual e consistente.",
    description: 'Essa base significa que agora voc\xEA pode tocar centenas de m\xFAsicas \u2013 e para celebrar, aqui est\xE1 uma das m\xFAsicas completas mais simples e ic\xF4nicas que voc\xEA pode tocar agora: "Love Me Do" dos Beatles (o primeiro single deles!).',
    why_perfect: "Esta m\xFAsica \xE9 perfeita para iniciantes terminando um curso de acordes: usa apenas 3 acordes abertos b\xE1sicos (G, C, D \u2013 alguns dos primeiros que voc\xEA provavelmente aprendeu), tem um ritmo divertido e animado, e inclui o famoso riff de gaita (que voc\xEA pode tocar no viol\xE3o se quiser). \xC9 energ\xE9tica, instantaneamente reconhec\xEDvel e far\xE1 voc\xEA se sentir como um verdadeiro Beatle!",
    chord_review: "Diagramas de Revis\xE3o de Acordes",
    chord_review_desc: "Estes s\xE3o acordes essenciais da sua jornada de 30 dias:",
    chord_g: "G: 320003",
    chord_c: "C: x32010",
    chord_d: "D: xx0232 (opcional para a ponte \u2013 a m\xFAsica principal \xE9 principalmente G e C!)",
    how_to_play: "Como Tocar",
    no_capo: "N\xE3o precisa de capotraste \u2013 toque na afina\xE7\xE3o padr\xE3o.",
    strumming_pattern: "Padr\xE3o de Dedilhado F\xE1cil:",
    strumming_pattern_desc: "Baixo-Baixo-Alto-Alto-Baixo-Alto (D DU UDU) \u2013 mantenha constante e divertido, como um beat rock dos anos 60. Comece devagar!",
    structure: "A m\xFAsica \xE9 principalmente verso + refr\xE3o repetindo G e C, com uma ponte curta.",
    verse_chorus: "Verso/Refr\xE3o (Acordes sobre a Letra):",
    bridge: "Ponte (opcional \u2013 adiciona D):",
    harmonica_riff: "Riff de Gaita no Viol\xE3o (B\xF4nus Divertido):",
    harmonica_riff_desc: "O famoso riff de introdu\xE7\xE3o s\xE3o notas simples no viol\xE3o \u2013 f\xE1cil de adicionar quando voc\xEA estiver confort\xE1vel com os acordes.",
    important_tips: "Dicas Importantes",
    tip_1: "Foque nas mudan\xE7as r\xE1pidas entre G e C \u2013 voc\xEA praticou muito isso!",
    tip_2: "Cante junto alto \u2013 \xE9 uma m\xFAsica que transmite energia positiva.",
    tip_3: "Isso prova o quanto voc\xEA chegou: apenas alguns acordes b\xE1sicos criam um hit mundial!",
    play_audio: "Tocar \xC1udio",
    final_message: "Parab\xE9ns! Voc\xEA completou 30 Acordes em 30 Dias + esta m\xFAsica b\xF4nus. Agora voc\xEA \xE9 um verdadeiro guitarrista \u2013 continue tocando todos os dias e compartilhe sua vers\xE3o de 'Love Me Do'! \u{1F3B8}"
  }
};

// src/lib/mcp/content.ts
var copyByLocale = {
  "en-US": content_default.chords ?? {},
  "pt-BR": content_default2.chords ?? {}
};
var STRINGS = ["6 (E low)", "5 (A)", "4 (D)", "3 (G)", "2 (B)", "1 (E high)"];
var FINGER_NAMES = {
  "1": "index",
  "2": "middle",
  "3": "ring",
  "4": "pinky"
};
function chordCopy(name, locale) {
  return copyByLocale[locale][name] ?? {};
}
function findChord(name) {
  const index = chords.findIndex(
    (c) => c.name.toLowerCase() === name.trim().toLowerCase()
  );
  return index < 0 ? void 0 : { chord: chords[index], day: index + 1 };
}
function chordForDay(day) {
  return chords[day - 1];
}
function totalDays() {
  return chords.length;
}
function allChords() {
  return chords;
}
function stringByString(chord) {
  return chord.fingering.map((fret, i) => {
    const label = `String ${STRINGS[i]}`;
    if (fret === "x") return `${label}: do not play (muted)`;
    if (fret === "0") return `${label}: open string (do not press)`;
    const finger = FINGER_NAMES[chord.fingers[i]];
    return `${label}: press fret ${fret}${finger ? ` with the ${finger} finger` : ""}`;
  });
}
function asciiDiagram(chord) {
  const header = chord.fingering.map((fret) => fret === "x" ? "x" : fret === "0" ? "o" : " ").join("--");
  const pressed = chord.fingering.map((f) => f === "x" || f === "0" ? 0 : Number(f)).filter((f) => f > 0);
  const maxFret = pressed.length ? Math.max(...pressed) : 3;
  const rows = [header, "=================="];
  for (let fret = 1; fret <= Math.max(3, maxFret); fret++) {
    const line = chord.fingering.map((f, i) => Number(f) === fret ? chord.fingers[i] || "*" : "|").join("--");
    rows.push(`${line}  ${fret}`);
  }
  return rows.join("\n");
}
function chordSummary(name, locale) {
  const found = findChord(name);
  if (!found) return void 0;
  const copy = chordCopy(found.chord.name, locale);
  return {
    name: found.chord.name,
    day: found.day,
    fullName: copy.fullName ?? found.chord.name,
    difficulty: copy.difficulty ?? null,
    fingering: found.chord.fingering,
    fingers: found.chord.fingers,
    placement: stringByString(found.chord),
    diagram: asciiDiagram(found.chord),
    instructions: copy.instructions ?? null,
    tip: copy.tip ?? null,
    commonSongs: found.chord.commonSongs ?? []
  };
}

// src/lib/mcp/tools/list-chords.ts
var list_chords_default = defineTool({
  name: "list_chords",
  title: "List the 30-day chord journey",
  description: "List every guitar chord in the 30-day journey, in learning order, with its day number, full name and difficulty.",
  inputSchema: {
    locale: z.enum(["en-US", "pt-BR"]).optional().describe("Language of the chord names and difficulty labels. Defaults to en-US.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ locale }) => {
    const lang = locale ?? "en-US";
    const items = allChords().map((chord, index) => {
      const copy = chordCopy(chord.name, lang);
      return {
        day: index + 1,
        name: chord.name,
        fullName: copy.fullName ?? chord.name,
        difficulty: copy.difficulty ?? null
      };
    });
    const text = items.map((c) => `Day ${c.day}: ${c.name} (${c.fullName})${c.difficulty ? ` \u2014 ${c.difficulty}` : ""}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { totalDays: totalDays(), chords: items }
    };
  }
});

// src/lib/mcp/tools/get-chord.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z2 } from "npm:zod@^3.23.8";
var get_chord_default = defineTool2({
  name: "get_chord",
  title: "Get how to play a chord",
  description: "Get everything needed to play one chord: which string each finger presses, an ASCII diagram, a beginner tip and famous songs that use it.",
  inputSchema: {
    name: z2.string().describe("Chord name as shown in the app, e.g. Em, Am, C, G, Dm."),
    locale: z2.enum(["en-US", "pt-BR"]).optional().describe("Language of the explanation text. Defaults to en-US.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name, locale }) => {
    const summary = chordSummary(name, locale ?? "en-US");
    if (!summary) {
      throw new ToolError(
        `Unknown chord "${name}". Use list_chords to see the 30 chords in the journey.`
      );
    }
    const lines = [
      `${summary.name} \u2014 ${summary.fullName} (day ${summary.day}${summary.difficulty ? `, ${summary.difficulty}` : ""})`,
      "",
      ...summary.placement,
      "",
      summary.diagram
    ];
    if (summary.instructions) lines.push("", summary.instructions);
    if (summary.tip) lines.push("", `Tip: ${summary.tip}`);
    if (summary.commonSongs.length) lines.push("", `Songs: ${summary.commonSongs.join("; ")}`);
    return {
      content: [{ type: "text", text: lines.join("\n") }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/get-daily-practice.ts
import { defineTool as defineTool3, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@2.0.4";
import { z as z3 } from "npm:zod@^3.23.8";
var PATTERNS = [
  { name: "Down only", notation: "D D D D", bpm: 60 },
  { name: "Down, down-up", notation: "D  D U", bpm: 70 },
  { name: "Down down-up up-down-up", notation: "D D U U D U", bpm: 80 }
];
var get_daily_practice_default = defineTool3({
  name: "get_daily_practice",
  title: "Get a day's practice routine",
  description: "Get the 5-10 minute routine for one day of the journey: today's chord, the chords to review, a strumming pattern with a suggested BPM, and a common mistake to avoid.",
  inputSchema: {
    day: z3.number().int().describe("Day of the journey, from 1 to 30."),
    locale: z3.enum(["en-US", "pt-BR"]).optional().describe("Language of the explanation text. Defaults to en-US.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ day, locale }) => {
    const total = totalDays();
    if (day < 1 || day > total) {
      throw new ToolError2(`Day must be between 1 and ${total}.`);
    }
    const chord = chordForDay(day);
    if (!chord) throw new ToolError2(`No chord found for day ${day}.`);
    const lang = locale ?? "en-US";
    const copy = chordCopy(chord.name, lang);
    const review = Array.from(
      { length: Math.min(3, day - 1) },
      (_, i) => chordForDay(day - 1 - i)?.name
    ).filter((n) => Boolean(n));
    const pattern = PATTERNS[Math.min(PATTERNS.length - 1, Math.floor((day - 1) / 10))];
    const routine = {
      day,
      chord: chord.name,
      fullName: copy.fullName ?? chord.name,
      difficulty: copy.difficulty ?? null,
      placement: stringByString(chord),
      practiceToday: `Play ${chord.name} slowly until every string rings clean, then switch between ${chord.name}${review.length ? ` and ${review.join(", ")}` : ""} without stopping the strum.`,
      review,
      strumming: pattern,
      commonMistake: "Pressing with the flat pad of the finger or too far from the fret, which makes strings buzz or sound muted.",
      tip: copy.tip ?? "Short and daily beats long and rare. If it hurts, stop \u2014 pain is not progress."
    };
    const text = [
      `Day ${day} \u2014 ${routine.chord} (${routine.fullName})`,
      "",
      `What to practice: ${routine.practiceToday}`,
      `Strumming: ${pattern.notation} at about ${pattern.bpm} BPM (${pattern.name})`,
      `Common mistake: ${routine.commonMistake}`,
      `Tip: ${routine.tip}`,
      "",
      ...routine.placement
    ].join("\n");
    return { content: [{ type: "text", text }], structuredContent: routine };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "chord-a-day-journey",
  title: "chord-a-day-journey",
  version: "0.1.0",
  instructions: "Tools for the 30-day beginner guitar journey. Use `list_chords` to see the chord order, `get_chord` for how to play one chord, and `get_daily_practice` for a day's 5-10 minute routine. Content is public and available in English (en-US) and Brazilian Portuguese (pt-BR).",
  tools: [list_chords_default, get_chord_default, get_daily_practice_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
